import Foundation

/// Utility for formatting and working with file sizes, dates, and paths.
struct FormatUtils {
    
    static func humanReadableSize(_ bytes: Int64) -> String {
        ByteCountFormatter.string(fromByteCount: bytes, countStyle: .file)
    }
    
    static func relativePath(_ absolutePath: String) -> String {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        return absolutePath.replacingOccurrences(of: home, with: "~")
    }
    
    static let timestampFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd HH:mm:ss"
        return f
    }()
    
    static let shortTimeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HH:mm:ss"
        return f
    }()
}

/// App-wide constants
struct BlackBoxConstants {
    static let appName = "BlackBox"
    static let vaultDirectoryName = ".BlackBox/Vault"
    static let maxFileScanSize: Int = 10_000_000 // 10MB
    static let vaultRetentionHours: TimeInterval = 172800 // 48 hours
    
    // Shredder passes
    static let shredderPasses = 3
    
    // MARK: - Telemetry Domain Lists (500+ domains)
    
    // Apple Telemetry & Analytics Domains
    static let appleTelemetryDomains = [
        // Core Apple Telemetry
        "metrics.apple.com",
        "xp.apple.com",
        "telemetry.apple.com",
        "diagnosic.apple.com",
        "analytics.apple.com",
        "iadcontent.apple.com",
        "iadsdk.apple.com",
        "securemetrics.apple.com",
        "supportmetrics.apple.com",
        "metrics.icloud.com",
        "experiments.apple.com",
        "feedbackws.apple.com",
        "radarsubmissions.apple.com",
        "idiagnostics.apple.com",
        "pancake.apple.com",
        "api-glb-pdx.smoot.apple.com",
        "api-glb-usw.smoot.apple.com",
        "smoot.apple.com",
        "xp-cdn.apple.com",
        "notes-analytics.apple.com",
        "news-events.apple.com",
        "stocks-analytics-events.apple.com",
        "weather-analytics-events.apple.com",
        "books-analytics-events.apple.com",
        "health-analytics-events.apple.com",
        "fitness-analytics-events.apple.com",
        "wallet-analytics-events.apple.com",
        "fmf-analytics-events.apple.com",
        "fmip-analytics-events.apple.com",
        "home-analytics-events.apple.com",
        "music-analytics-events.apple.com",
        "podcasts-analytics-events.apple.com",
        "maps-analytics-events.apple.com",
        "photos-analytics-events.apple.com",
        "reminders-analytics-events.apple.com",
        "safari-analytics-events.apple.com",
        "mail-analytics-events.apple.com",
        "messages-analytics-events.apple.com",
        "facetime-analytics-events.apple.com",
        "tv-analytics-events.apple.com",
        "appletv-analytics-events.apple.com",
        "siri-analytics-events.apple.com",
        "spotlight-analytics-events.apple.com",
        "calendar-analytics-events.apple.com",
        "contacts-analytics-events.apple.com",
        "clock-analytics-events.apple.com",
        "shortcuts-analytics-events.apple.com",
        "screen-time-analytics-events.apple.com",
        "tips-analytics-events.apple.com",
        // Siri & Assistant
        "guzzoni.apple.com",
        "dejavu.apple.com",
        "swallow.apple.com",
        "lcdn-registration.apple.com",
        // Apple Ads
        "advertising.apple.com",
        "iad.apple.com",
        "iad-ext.apple.com",
        "searchads.apple.com",
        "doubleclick-apple.com",
    ]
    
    // Third-Party Telemetry, Analytics, & Tracking Domains
    static let thirdPartyTelemetryDomains = [
        // Google Analytics & Tracking
        "clients4.google.com",
        "connectivitycheck.gstatic.com",
        "update.googleapis.com",
        "crashlyticsreports-pa.googleapis.com",
        "www.google-analytics.com",
        "ssl.google-analytics.com",
        "analytics.google.com",
        "firebaseinstallations.googleapis.com",
        "firebaselogging.googleapis.com",
        "app-measurement.com",
        "googleads.g.doubleclick.net",
        "pagead2.googlesyndication.com",
        "adservice.google.com",
        "www.googletagmanager.com",
        "www.googletagservices.com",
        "ad.doubleclick.net",
        "stats.g.doubleclick.net",
        "cm.g.doubleclick.net",
        "googleadservices.com",
        "fundingchoicesmessages.google.com",
        "google-analytics.bi.owlting.com",
        "ampcid.google.com",
        "ogs.google.com",
        // Microsoft Telemetry
        "incoming.telemetry.mozilla.org",
        "telemetry.firefox.com",
        "dc.services.visualstudio.com",
        "vortex.data.microsoft.com",
        "settings-win.data.microsoft.com",
        "activity.windows.com",
        "watson.telemetry.microsoft.com",
        "watson.microsoft.com",
        "statsfe2.ws.microsoft.com",
        "corpext.msitadfs.glbdns2.microsoft.com",
        "compatexchange.cloudapp.net",
        "cs1.wpc.v0cdn.net",
        "df.telemetry.microsoft.com",
        "diagnostics.support.microsoft.com",
        "fe2.update.microsoft.com.akadns.net",
        "feedback.microsoft-hohm.com",
        "feedback.search.microsoft.com",
        "feedback.windows.com",
        "oca.telemetry.microsoft.com",
        "oca.telemetry.microsoft.com.nsatc.net",
        "pre.footprintpredict.com",
        "redir.metaservices.microsoft.com",
        "reports.wes.df.telemetry.microsoft.com",
        "services.wes.df.telemetry.microsoft.com",
        "settings-sandbox.data.microsoft.com",
        "sqm.df.telemetry.microsoft.com",
        "sqm.telemetry.microsoft.com",
        "sqm.telemetry.microsoft.com.nsatc.net",
        "statsfe1.ws.microsoft.com",
        "statsfe2.update.microsoft.com.akadns.net",
        "survey.watson.microsoft.com",
        "telecommand.telemetry.microsoft.com",
        "telemetry.appex.bing.net",
        "telemetry.microsoft.com",
        "telemetry.urs.microsoft.com",
        "vortex-sandbox.data.microsoft.com",
        "vortex-win.data.microsoft.com",
        // Facebook / Meta
        "graph.facebook.com",
        "pixel.facebook.com",
        "an.facebook.com",
        "ads.facebook.com",
        "www.facebook.com",
        "connect.facebook.net",
        "staticxx.facebook.com",
        "web.facebook.com",
        "edge-chat.facebook.com",
        "external-iad3-1.xx.fbcdn.net",
        "fbcdn.net",
        "scontent.xx.fbcdn.net",
        "analytics.instagram.com",
        "graph.instagram.com",
        "i.instagram.com",
        // Twitter / X
        "analytics.twitter.com",
        "ads-api.twitter.com",
        "syndication.twitter.com",
        "t.co",
        "tr.snapchat.com",
        // Amazon
        "device-metrics-us.amazon.com",
        "device-metrics-us-2.amazon.com",
        "fls-na.amazon.com",
        "mads.amazon.com",
        "aax.amazon.com",
        "aax-us-east.amazon-adsystem.com",
        "s.amazon-adsystem.com",
        "z-na.amazon-adsystem.com",
        "aan.amazon.com",
        "unagi.amazon.com",
        "unagi-na.amazon.com",
        // Adobe
        "2o7.net",
        "omtrdc.net",
        "demdex.net",
        "everesttech.net",
        "adobedtm.com",
        "assets.adobedtm.com",
        "dpm.demdex.net",
        "cm.everesttech.net",
        "cc-api-data.adobe.io",
        "geo2.adobe.com",
        // Crash / Error Reporting
        "sentry.io",
        "o0.ingest.sentry.io",
        "crashlytics.com",
        "api.crashlytics.com",
        "reports.crashlytics.com",
        "settings.crashlytics.com",
        "firebase-settings.crashlytics.com",
        "bugsnag.com",
        "notify.bugsnag.com",
        "sessions.bugsnag.com",
        "api.rollbar.com",
        "raygun.io",
        "api.raygun.io",
        // Advertising Networks
        "doubleclick.net",
        "ad.doubleclick.net",
        "ads.yahoo.com",
        "analytics.yahoo.com",
        "advertising.com",
        "adsrvr.org",
        "adnxs.com",
        "openx.net",
        "pubmatic.com",
        "rubiconproject.com",
        "casalemedia.com",
        "criteo.com",
        "bidswitch.net",
        "outbrain.com",
        "taboola.com",
        "sharethrough.com",
        "contextweb.com",
        "indexexchange.com",
        "spotxchange.com",
        "brightcove.com",
        "teads.tv",
        "yieldmo.com",
        "media.net",
        "conversantmedia.com",
        "sovrn.com",
        "richaudience.com",
        "smartadserver.com",
        "33across.com",
        "triplelift.com",
        "liveintent.com",
        // Tracking & Analytics
        "hotjar.com",
        "script.hotjar.com",
        "vars.hotjar.com",
        "in.hotjar.com",
        "mixpanel.com",
        "api.mixpanel.com",
        "decide.mixpanel.com",
        "cdn.mxpnl.com",
        "api.amplitude.com",
        "cdn.amplitude.com",
        "heapanalytics.com",
        "cdn.heapanalytics.com",
        "fullstory.com",
        "rs.fullstory.com",
        "segment.io",
        "api.segment.io",
        "cdn.segment.com",
        "api.segment.com",
        "hubspot.com",
        "track.hubspot.com",
        "js.hs-analytics.net",
        "js.hs-banner.com",
        "js.hsadspixel.net",
        "js.usemessages.com",
        "braze.com",
        "sdk.iad-01.braze.com",
        "rest.iad-01.braze.com",
        "customer.io",
        "track.customer.io",
        "intercom.io",
        "api-iam.intercom.io",
        "js.intercomcdn.com",
        "widget.intercom.io",
        "optimizely.com",
        "cdn.optimizely.com",
        "logx.optimizely.com",
        "kissmetrics.com",
        "trk.kissmetrics.com",
        "crazyegg.com",
        "script.crazyegg.com",
        "mouseflow.com",
        "o2.mouseflow.com",
        "clarity.ms",
        "c.clarity.ms",
        "clicky.com",
        "in.getclicky.com",
        "static.getclicky.com",
        "woopra.com",
        "static.woopra.com",
        "matomo.cloud",
        "piwik.pro",
        "plausible.io",
        "api.usefathom.com",
        // Data Brokers & People-Search
        "acxiom.com",
        "epsilon.com",
        "oracle.com",
        "bluekai.com",
        "addthis.com",
        "stags.bluekai.com",
        "tags.bluekai.com",
        "bkrtx.com",
        "rlcdn.com",
        "exelator.com",
        "pippio.com",
        "agkn.com",
        "adsymptotic.com",
        "tapad.com",
        "liveramp.com",
        "iddqd.com",
        "neustar.biz",
        "agkn.com",
        // CDN Tracking Beacons
        "cdn.cookielaw.org",
        "geolocation.onetrust.com",
        "cdn.onetrust.com",
        "optanon.blob.core.windows.net",
        "privacymanager.io",
        "consent.cookiebot.com",
        "consentcdn.cookiebot.com",
        "consent.cookiefirst.com",
        // Social Media Tracking Pixels
        "snap-analytics.appspot.com",
        "sc-analytics.appspot.com",
        "tr.snapchat.com",
        "ct.pinterest.com",
        "analytics.pinterest.com",
        "ads.pinterest.com",
        "trk.pinterest.com",
        "t.tiktok.com",
        "analytics.tiktok.com",
        "ads-sg.tiktok.com",
        "business-api.tiktok.com",
        "analytics-sg.tiktok.com",
        "log.byteoversea.com",
        "p16-tiktokcdn-com.akamaized.net",
        "analytics-api2.reddit.com",
        "events.reddit.com",
        "rereddit.com",
        "alb.reddit.com",
        "ads.reddit.com",
        "d.reddit.com",
        // Miscellaneous Trackers
        "bat.bing.com",
        "a.clarity.ms",
        "scorecardresearch.com",
        "sb.scorecardresearch.com",
        "quantserve.com",
        "pixel.quantserve.com",
        "chartbeat.com",
        "ping.chartbeat.net",
        "static.chartbeat.com",
        "cdn.krxd.net",
        "beacon.krxd.net",
        "apiservices.krxd.net",
        "consumer.krxd.net",
        "usabilla.com",
        "w.usabilla.com",
        // Push Notification Tracking
        "onesignal.com",
        "api.onesignal.com",
        "img.onesignal.com",
        "cdn.onesignal.com",
        "pushwoosh.com",
        "cp.pushwoosh.com",
        "log.pushwoosh.com",
        // Mobile Analytics
        "app.adjust.com",
        "s2s.adjust.com",
        "app.appsflyer.com",
        "launches.appsflyer.com",
        "inapps.appsflyer.com",
        "t.appsflyer.com",
        "events.appsflyer.com",
        "kochava.com",
        "control.kochava.com",
        "attribution.report",
        "branch.io",
        "api.branch.io",
        "cdn.branch.io",
        "app.link",
        "bnc.lt",
        "singular.net",
        "sdk-api-v1.singular.net",
        "i.liadm.com",
        // E-commerce & Retail Tracking
        "cdn.shopify.com",
        "monorail-edge.shopifysvc.com",
        "c.paypal.com",
        "t.paypal.com",
        "tracking.epicgames.com",
        "tracking.unrealengine.com",
        // Additional Well-Known Trackers
        "pixel.wp.com",
        "stats.wp.com",
        "public-api.wordpress.com",
        "cloudflareinsights.com",
        "static.cloudflareinsights.com",
        "newrelic.com",
        "js-agent.newrelic.com",
        "bam.nr-data.net",
        "bam-cell.nr-data.net",
        "log.pinterest.com",
        "widgets.pinterest.com",
        "api.mapbox.com",
        "events.mapbox.com",
        // Gaming & Entertainment Telemetry
        "telemetry.gog.com",
        "tracking.epicgames.com",
        "metrics.gaijin.net",
        "analytics.riotgames.com",
        "data.ea.com",
        "telemetry.ubi.com",
        "tracker.ubi.com",
        "stats.ubi.com",
        "redshell.io",
        "api.gameanalytics.com",
        "rubick.gameanalytics.com",
        "unity3d.com",
        "config.uca.cloud.unity3d.com",
        "cdp.cloud.unity3d.com",
        "perf-events.cloud.unity3d.com",
        "ecommerce.iap.unity3d.com",
        "userreporting.cloud.unity3d.com",
        "analytics.cloud.unity3d.com",
        "prd-lngsight-eg.cloud.unity3d.com",
        "remote-config-proxy-prd.uca.cloud.unity3d.com",
        "steam-chat.com",
        "partner.steamgames.com",
        // IoT & Smart Home Telemetry
        "spectrum.s3.amazonaws.com",
        "data.flurry.com",
        "logs.roku.com",
        "cooper.logs.roku.com",
        "analytics.roku.com",
        "scribe.logs.roku.com",
        "p.typekit.net",
        "use.typekit.net",
        "fast.wistia.com",
        "pipedream.wistia.com",
        "embedwistia-a.akamaihd.net",
        "heapanalytics.com",
        "t.co",
        "fire-analytics.successfactors.com",
        "homekit-analytics.apple.com",
        "iot-logser.realtek.com.tw",
        "analytics.tuyaus.com",
        "log.tuyaus.com",
        "a.tuyacn.com",
        // Enterprise Analytics & APM
        "rum.hlx.page",
        "collector.github.com",
        "api.github.com/_private/browser/stats",
        "alive.github.com",
        "copilot-telemetry.githubusercontent.com",
        "eastus.livediagnostics.monitor.azure.com",
        "westus.livediagnostics.monitor.azure.com",
        "dc.applicationinsights.azure.com",
        "rt.applicationinsights.azure.com",
        "live.applicationinsights.azure.com",
        "js.monitor.azure.com",
        "centralus.livediagnostics.monitor.azure.com",
        "in.appcenter.ms",
        "gate.hockeyapp.net",
        "api.appcenter.ms",
        "analytics.plex.tv",
        "metrics.plex.tv",
        "analytics.sonos.com",
        "anaconda.com",
        "repo.anaconda.com",
        // Email & Marketing Tracking
        "link.mail.beehiiv.com",
        "open.substack.com",
        "track.mailchimp.com",
        "email.mailgun.com",
        "o1.email.dynect.net",
        "mandrillapp.com",
        "email.postmarkapp.com",
        "tracking.sendgrid.net",
        "click.pstmrk.it",
        "email.campaign.grammarly.com",
        "track.bronto.com",
        "link.newsletters.nytimes.com",
        "tracking.tldrnewsletter.com",
        "sparkpostmail.com",
        "mta.email.amazonses.com",
        "feedproxy.google.com",
        "email.mg.convertkit.com",
        "track.aftership.com",
        // Consent & Privacy Management (Ironic Trackers)
        "cdn.iubenda.com",
        "cs.iubenda.com",
        "consent.trustarc.com",
        "preferences-mgr.truste.com",
        "consent-pref.trustarc.com",
        "cdn.privacy-center.org",
        "app.securiti.ai",
        "app-consent.securiti.ai",
        "consent.linksynergy.com",
        // DNS & Telemetry Sidechannels
        "use-application-dns.net",
        "mask.icloud.com",
        "mask-h2.icloud.com",
        "dns.nextdns.io",
        "report-uri.cloudflare.com",
        "nel.cloudflare.com",
        "sentry.cloudflare.com",
        "sparrow.cloudflare.com",
        "canary.discord.com",
        "sentry.discord.com",
        // Automotive Telemetry
        "api.connected-car.io",
        "analytics.tesla.com",
        "telemetry.vw.com",
        "connectivity.audi.com",
        "analytics.bmw.com",
        "telemetry.mbusa.com",
        "data.ford.com",
        "api.smartcar.com",
        "vehicle-data.gm.com",
        // Health & Fitness Tracking
        "api.fitbit.com",
        "telemetry.fitbit.com",
        "analytics.garmin.com",
        "di-api.redbullmobileenergy.com",
        "api.myfitnesspal.com",
        "analytics.strava.com",
        "vitals.vercel-insights.com",
        // VPN & Security Analytics
        "log.expressvpn.com",
        "telemetry.nordsec.com",
        "analytics.surfshark.com",
        "api.avg.com",
        "ncc.avast.com",
        "analytics.avast.com",
        "telemetry.norton.com",
        "telemetry.mcafee.com",
        "shstat.mcafee.com",
        // Streaming & Media
        "telemetry.spotify.com",
        "spclient.wg.spotify.com",
        "adeventtracker.spotify.com",
        "log.spotify.com",
        "audio-fa.spotifycdn.com",
        "pixel.spotify.com",
        "sentry.spotify.com",
        "api-partner.spotify.com",
        "telemetry.netflix.com",
        "ichnaea.netflix.com",
        "customerevents.netflix.com",
        "api-global.netflix.com",
        "presentationtracking.netflix.com",
        "nrdp.nccp.netflix.com",
        "assets.nflxext.com",
        "telemetry.hulu.com",
        "ads.hulu.com",
        "t.hulu.com",
        "telemetry.cbs.com",
        "telemetry.paramountplus.com",
        "log.disneyplus.com",
        "telemetry.disneystreaming.com",
        "bam-sdk-configs.bamgrid.com",
        "billing.disneyplus.com",
        // Developer & CI/CD Analytics
        "telemetry.hashicorp.com",
        "checkpoint-api.hashicorp.com",
        "telemetry.gitlab.com",
        "snowplow.trx.gitlab.net",
        "sentry.gitlab.net",
        "telemetry.jetbrains.com",
        "resources.jetbrains.com",
        "data.services.jetbrains.com",
        "download.jetbrains.com",
        "telemetry.docker.com",
        "desktop.docker.com",
        "hub.docker.com",
        "registry-1.docker.io",
        "notify.bugsnag.com",
    ]
}
